# Generated by Django 3.2.9 on 2022-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmartapp', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
                ('rupees', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
