# Generated by Django 3.2.9 on 2022-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmartapp', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
