# Generated by Django 3.2.9 on 2022-11-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medmartapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='medmartapp.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='medmartapp.service'),
            preserve_default=False,
        ),
    ]
