# Generated by Django 3.2.9 on 2022-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmartapp', '0005_auto_20221122_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
