# Generated by Django 3.2.9 on 2022-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medmartapp', '0006_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
